name: laravel-project-abc

services:
  mysql:
    image: mysql:8.4
    ports:
      - "3366:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6380"
    volumes:
      - redis_data:/data
      - ./scripts/config/redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf"]

  laravel-magic:
    container_name: laravel-magic-backend-service
    build:
      context: .
      dockerfile: dockerfile.yaml
    ports:
      - "8425:8425"
    volumes:
      - .:/app
    depends_on:
      - mysql
      - redis
    # command: ["sleep", "infinity"]

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
