name: laravel-project-abc

services:
  mysql:
    image: mysql:8.4
    ports:
      - "3366:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

  laravel-magic:
    container_name: laravel-magic-backend-service
    build:
      context: .
      dockerfile: dockerfile.yaml
    ports:
      - "8425:8425"
    volumes:
      - .:/app
    depends_on:
      - mysql
    # command: ["sleep", "infinity"]

volumes:
  mysql_data:
    driver: local
